### ISSUE TITLE
model evaluation process

### ISSUE THREAD

**Issue by bogsnork** [bogsnork/nectarvision#8]
Create a process to evaluate models

**Comment by bogsnork** [comment]
- [x] sort out folder structure for logs and weights
- [x] fix the issue with image magick to allow visualisation #11 or find an alternative to image magick
- [x] choose some sample images to document progress
- [ ] sort out `predict` code #12 
- [ ] create simple api (see #9 )
- [ ] get rid of old weights files to make space

**Comment by bogsnork** [comment]
DH selected following sample images: 

- IMG_3019	Centaurea nigra, Ranunculus spp., Rhinanthus minor and 1 Leucanthemum vulgare
- IMG_4001	Senecio jacobaea
- IMG_4409	Trifolium repens and Trifolium pratense
- IMG_4265	Angelica sylvestris
- IMG_4456	Prunella vulgaris
- IMG_4460	Trifolium pratense
- IMG_4468	Silene dioica/latifolia, Leucanthemum vulgare and Lotus spp.
- IMG_4567 	Achillea millefolium (and 1 or 2 yellow composite)
- IMG_4580	yellow composite
- IMG_4604	Stachys sylvatica
- IMG_4798	Symphytum spp.
- IMG_4783	Bellis perennis
- IMG_4821	Rubus fruticosus agg.
- IMG_5352	Cirsium arvense, Achillea millefoliium, Lotus spp.
- IMG_5349	Ranunculus spp. (and 1 Prunella vulgaris)
- IMG_5328	Heracleum sphondylium
- IMG_5277	Leucanthemum vulgare, Lotus spp., Vicia cracca
- IMG_5217	Taraxacum agg.
- IMG_5052	Cirsium vulgare
- IMG_5129	Knautia arvensis
- IMG_4998	Lathyrus pratensis
- IMG_4664	Vicia sepium/sativa and 1 Trifolium repens

**Comment by bogsnork** [comment]
Needed to revert back to previous callback to make it work (see c4585ab).  Unfortunately this means weights are just saved in the working directory for the time being.

**Comment by bogsnork** [comment]
looking good: Outputs from run `ssd_20200213-1727`
Epoch 5/5
125/125 - 536s - loss: 13.1707 - class_output_loss: 10.7165 - bbox_output_loss: 2.4542 - class_output_class_loss: 10.7165 - bbox_output_bbox_loss: 2.4542

![image](https://user-images.githubusercontent.com/23337510/74465878-1c93eb00-4e8e-11ea-9fc6-b426576b0220.png)

**Comment by bogsnork** [comment]
can't find these images
> * IMG_4265	Angelica sylvestris
>* IMG_4998 Lathyrus pratensis

**Comment by bogsnork** [comment]
hmmm....
![image](https://user-images.githubusercontent.com/23337510/75110565-741d1e00-5627-11ea-9c89-373eabdcfa54.png)

**Comment by bogsnork** [comment]
moving the predict visualisation into it's own issue #12
